const STORE='mt-risk-sim-v1';let DATA,state,undoStack=[];const labels={A:'Bij huidige risico-eigenaar laten',B:'Aanvullende informatie opvragen',C:'Opnemen als MT-risico',D:'Escaleren naar bestuur'};const scoreNames={grip:'Grip op risico\'s',eig:'Eigenaarschap & vertrouwen',uit:'Uitvoerbaarheid',strat:'Strategische slagkracht'};
async function boot(){DATA=await fetch('data/game-data.json').then(r=>r.json());state=load()||fresh();render();}
function fresh(){let starts={grip:+DATA.config["Startscore Grip op risico's"]||70,eig:+DATA.config['Startscore Eigenaarschap & vertrouwen']||70,uit:+DATA.config['Startscore Uitvoerbaarheid']||70,strat:+DATA.config['Startscore Strategische slagkracht']||70};return{round:1,mts:[1,2,3,4].map(i=>({id:i,name:`MT ${i}`,scores:{...starts},budget:+DATA.config['Startbudget kEUR']||10000,cap:+DATA.config['Startcapaciteit %']||100,current:'R1.1_START',line:1,step:1,managed:[],history:[],counters:{MICRO:0,ANALYSE:0,ESCAL:0,PREM_ESCAL:0,AFHOUD:0,GOOD_GOV:0},triggered:[],events:[],chosen:false}))};}
function load(){try{return JSON.parse(localStorage.getItem(STORE))}catch(e){return null}}function save(){localStorage.setItem(STORE,JSON.stringify(state))}function clamp(x){return Math.max(0,Math.min(100,x))}function scen(id){return DATA.scenarios.find(x=>x.Scenario_ID===id)}function effect(risk,ch){return DATA.effects.find(x=>x.Risico_ID===risk&&x.Keuze===ch)}function route(risk,ch){return DATA.routes.find(x=>x.Huidig_risico===risk&&x.Keuze===ch)}
function render(){let g=document.getElementById('grid');g.innerHTML='';state.mts.forEach(mt=>{let s=scen(mt.current)||DATA.scenarios.find(x=>x.Risico_ID===`R${mt.line}.${mt.step}`);let risk=s?.Risico_ID||'Einde';let desc=s?.Risicobeschrijving_variant||s?.Basis_risicobeschrijving||'Deze risicolijn is afgerond.';let card=document.createElement('section');card.className='mt-card';card.innerHTML=`<div class="mt-head"><h2>${mt.name}</h2><span class="eyebrow">Ronde ${state.round}</span></div><div class="risk"><div class="eyebrow">Actuele risicokaart · ${risk}</div><h3>${esc(s?.Titel||'Risicolijn afgerond')}</h3><p>${esc(desc)}</p><div class="meta">Afzender: ${esc(s?.Afzender||'-')} · Risico-eigenaar: ${esc(s?.Huidige_risico_eigenaar||'-')}</div>${mt.events.slice(-1).map(e=>`<div class="event">${esc(e)}</div>`).join('')}</div><div class="body"><div class="scores"><h4>Vier scorepijlers</h4>${score('grip',mt.scores.grip)}${score('eig',mt.scores.eig)}${score('uit',mt.scores.uit)}${score('strat',mt.scores.strat)}</div><div class="managed"><h4>Actieve MT-risico's (keuze C)</h4>${mt.managed.length?`<ul>${mt.managed.map(x=>`<li><strong>${esc(x.id)}</strong> ${esc(x.title)}</li>`).join('')}</ul>`:'<div class="empty">Nog geen risico’s door het MT opgenomen.</div>'}</div></div><div class="choice"><div class="buttons">${['A','B','C','D'].map(ch=>`<button class="${ch==='C'?'c':''}" ${mt.chosen?'disabled':''} onclick="preview(${mt.id},'${ch}')"><strong>${ch}</strong><br>${labels[ch]}</button>`).join('')}</div><div class="status">${mt.chosen?'Keuze voor deze ronde verwerkt.':'Nog geen keuze ingevoerd.'}</div></div>`;g.appendChild(card)});save()}
function score(k,v){let band=v>=80?'Goed':v>=60?'Redelijk':v>=40?'Onder druk':'Kritiek';return `<div class="score-row"><span>${scoreNames[k]}<br><small>${band}</small></span><div class="track"><div class="fill" style="width:${v}%"></div></div><strong>${v}</strong></div>`}
window.preview=function(id,ch){let mt=state.mts.find(x=>x.id===id);if(mt.chosen)return;let s=scen(mt.current),e=effect(s.Risico_ID,ch);if(!e)return alert('Geen besluiteffect gevonden.');let box=document.getElementById('modalBox');box.innerHTML=`<div class="eyebrow">${mt.name} · ${s.Risico_ID} · keuze ${ch}</div><h2>${labels[ch]}</h2><p>${esc(e.Gevolgbeschrijving||'')}</p><div class="effect-grid">${delta('Grip',e.Delta_grip)}${delta('Eigenaarschap',e.Delta_eigenaarschap_vertrouwen)}${delta('Uitvoerbaarheid',e.Delta_uitvoerbaarheid)}${delta('Strategische slagkracht',e.Delta_strategische_slagkracht)}</div><p><strong>Budget:</strong> ${signed(e.Budget_mutatie_kEUR)} k€ &nbsp; <strong>Capaciteit:</strong> ${signed(e.Capaciteit_mutatie_pct)}%</p><div class="modal-actions"><button class="secondary" onclick="closeModal()">Annuleren</button><button class="primary" onclick="commit(${id},'${ch}')">Besluit verwerken</button></div>`;document.getElementById('modal').classList.add('show')}
function delta(n,v){v=+v||0;return `<div class="pill">${n}<strong>${signed(v)}</strong></div>`}function signed(v){v=+v||0;return v>0?`+${v}`:`${v}`}
window.closeModal=()=>document.getElementById('modal').classList.remove('show');
window.commit=function(id,ch){undoStack.push(JSON.stringify(state));let mt=state.mts.find(x=>x.id===id),s=scen(mt.current),e=effect(s.Risico_ID,ch);mt.scores.grip=clamp(mt.scores.grip+(+e.Delta_grip||0));mt.scores.eig=clamp(mt.scores.eig+(+e.Delta_eigenaarschap_vertrouwen||0));mt.scores.uit=clamp(mt.scores.uit+(+e.Delta_uitvoerbaarheid||0));mt.scores.strat=clamp(mt.scores.strat+(+e.Delta_strategische_slagkracht||0));mt.budget+=(+e.Budget_mutatie_kEUR||0);mt.cap+=(+e.Capaciteit_mutatie_pct||0);if(ch==='C'&&!mt.managed.some(x=>x.id===s.Risico_ID))mt.managed.push({id:s.Risico_ID,title:s.Titel});applyFlag(mt,e.Gedragsflag,ch);mt.history.push({scenario:mt.current,risk:s.Risico_ID,choice:ch,effect:e.Gevolgbeschrijving});mt.next=route(s.Risico_ID,ch)?.Volgend_scenario_ID||null;mt.chosen=true;checkConditions(mt);closeModal();render()}
function applyFlag(mt,flag,ch){if(ch==='B')mt.counters.ANALYSE++;if(ch==='D')mt.counters.ESCAL++;if(flag==='MICROMANAGEMENT')mt.counters.MICRO++;if(['ONNODIGE_ESCALATIE','PREMATURE_ESCALATIE'].includes(flag))mt.counters.PREM_ESCAL++;if(flag==='ANALYSEVERLAMMING')mt.counters.ANALYSE++;}
function checkConditions(mt){for(const c of DATA.conditions){if(!c.Eenmalig||!mt.triggered.includes(c.Conditie_ID)){let m=String(c.Voorwaarde||'').match(/([A-Z_]+)\s*(>=|<)/);if(!m)continue;let key=m[1],op=m[2],v=counterVal(mt,key),d=+c.Drempel||0,hit=op==='>='?v>=d:v<d;if(hit&&c.Eenmalig){mt.triggered.push(c.Conditie_ID);mt.scores.grip=clamp(mt.scores.grip+(+c.Delta_grip||0));mt.scores.eig=clamp(mt.scores.eig+(+c.Delta_eigenaarschap||0));mt.scores.uit=clamp(mt.scores.uit+(+c.Delta_uitvoerbaarheid||0));mt.scores.strat=clamp(mt.scores.strat+(+c.Delta_strategische_slagkracht||0));mt.events.push(c['Aanvullende tekst / gebeurtenis'])}}}}
function counterVal(mt,k){return({MICRO:mt.counters.MICRO,ANALYSE:mt.counters.ANALYSE,PREM_ESCAL:mt.counters.PREM_ESCAL,ESCAL:mt.counters.ESCAL,AFHOUD:mt.counters.AFHOUD,GOOD_GOV:mt.counters.GOOD_GOV,ORG_GRIP:mt.scores.grip,ORG_EIG:mt.scores.eig,ORG_UIT:mt.scores.uit,ORG_STRAT:mt.scores.strat,INFO:mt.counters.ANALYSE})[k]??0}
document.getElementById('nextRound').onclick=()=>{if(!state.mts.every(x=>x.chosen))return alert('Nog niet alle vier MT’s hebben een keuze gemaakt.');undoStack.push(JSON.stringify(state));for(const mt of state.mts){if(mt.next){mt.current=mt.next;let s=scen(mt.current);mt.line=+(s?.Risico_ID?.split('.')[0].slice(1)||mt.line);mt.step=+(s?.Risico_ID?.split('.')[1]||mt.step)}else{if(mt.line<4){mt.line++;mt.step=1;mt.current=`R${mt.line}.1_START`}else mt.current=null}mt.chosen=false;mt.next=null}state.round++;render()};
document.getElementById('undo').onclick=()=>{if(!undoStack.length)return alert('Geen actie om ongedaan te maken.');state=JSON.parse(undoStack.pop());render()};document.getElementById('reset').onclick=()=>{if(confirm('Hele spelstatus wissen en opnieuw starten?')){localStorage.removeItem(STORE);state=fresh();undoStack=[];render()}};
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}boot();