const params=new URLSearchParams(location.search);const id=+(params.get('mt')||1);const cfg=window.SUPABASE_CONFIG;const sb=(window.supabase&&cfg)?window.supabase.createClient(cfg.url,cfg.publishableKey):null;
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function parseRisk(raw){try{const x=JSON.parse(raw||'');if(x&&typeof x==='object'&&!Array.isArray(x))return x}catch(e){}const t=String(raw||'');const parts=t.split(/\n\nOnzekere gebeurtenis\n/);return{context:(parts[0]||'').replace(/^Context\n/,''),event:parts[1]||'',risks:{}}}
function parseConditions(raw){try{const x=JSON.parse(raw||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function parseManaged(raw){if(Array.isArray(raw))return raw;try{const x=JSON.parse(raw||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function riskClass(v){return 'risk-'+String(v||'').toLowerCase()}
function render(row){document.getElementById('team').textContent=`MT ${id}`;if(!row){document.getElementById('title').textContent='Nog geen actuele risicokaart beschikbaar';document.getElementById('context').textContent='Wacht tot de docent de simulatie heeft gestart.';return;}const d=parseRisk(row.risico_beschrijving);document.getElementById('round').textContent=`Ronde ${row.ronde}`;document.getElementById('risk').textContent=`Actuele risicokaart · ${row.risico_code||''}`;document.getElementById('title').textContent=row.risico_titel||'';document.getElementById('context').textContent=d.context||'-';document.getElementById('event').textContent=d.event||'-';document.getElementById('meta').textContent=`Afzender: ${row.afzender||'-'}`;
 const order=['Bereikbaarheid','Leefbaarheid','Veiligheid','Imago','Kosten'];document.getElementById('riskProfile').innerHTML=order.map(k=>`<div class="risk-pill ${riskClass(d.risks?.[k])}"><span>${k}</span><strong>${esc(d.risks?.[k]||'-')}</strong></div>`).join('');
 const cond=parseConditions(row.risico_eigenaar);document.getElementById('conditions').innerHTML=cond.length?cond.map(x=>`<div class="condition-item">${esc(x)}</div>`).join(''):'<div class="empty">Er zijn nog geen aanvullende condities of gebeurtenissen actief.</div>';
 const managed=parseManaged(row.actieve_mt_risicos);document.getElementById('managedRisks').innerHTML=managed.length?`<ul>${managed.map(x=>`<li><strong>${esc(x.id||'')}</strong> ${esc(x.title||'')}</li>`).join('')}</ul>`:'<div class="empty">Nog geen risico’s door het MT opgenomen.</div>';
}
async function load(){if(!sb)return;let {data,error}=await sb.from('mt_state').select('*').eq('mt_id',id).single();if(error){console.error(error);return;}render(data)}
async function boot(){document.getElementById('team').textContent=`MT ${id}`;await load();if(!sb)return;sb.channel(`mt-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'mt_state',filter:`mt_id=eq.${id}`},payload=>render(payload.new)).subscribe(status=>{let el=document.getElementById('live');if(el)el.textContent=status==='SUBSCRIBED'?'● Live verbonden':'○ Verbinden…';});}boot();
